version: '3.5'
services:

  tomcat:
    build:
      context: .
      args:
        WILDFLY_NAME: wildfly_1
        CLUSTER_PW: secret_password
    image: wildfly_1
    ports:
    - 8082:8080
    networks:
      wildfly_network:
networks:
  wildfly_network:
    ipam:
      driver: default